#!/usr/bin/env bash
# Script that display information about subdomains.
subName=$2
subNames=("www" "lb-01" "web-01" "web-02")

if [ $# -eq 2 ]
then
    INFO=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
    echo "The subdomain $subName is a A record and points to $INFO"
else
    for i in "${subNames[@]}"
do
    INFO=$(dig $i.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
    echo "The subdomain $i is a A record and points to $INFO"
done
fi
