#!/usr/bin/env bash
# Install nginx on your web-01 server.
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html
sudo service nginx restart
