#!/usr/bin/env bash
# Configure web-02 to be identical to web-01 and HTTP response contains a custom header.
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo sed -i '29 a add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx restart
