#!/usr/bin/env bash
#Accepts a string as an argument and 
#Ping the IP 5 times
numargs=0
for count in $@
do
    (( numargs++ ))
done
if [ $numargs == 1 ]
then 
ping -c 5 $1
else
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi