#!/usr/bin/env bash
# This script is displaying "Best School" 20 times
#excep some numbers implement the case statements
i=0
while ((i < 20))
do
    ((i++))
    echo "$i"
    case $i in
        "4" )
            echo "bad luck from China"
            ;;
        "9" )
            echo "bad luck from Japan"
            ;;
        "17" )
            echo "bad luck from Italy"
            ;;
    esac
done