#!/usr/bin/env bash
# This script displays the time for 12 hours 
#and 59 minutes:
i=0
while ((i <= 12)); do
    j=1
    echo "Hour: $i"
    ((i++))
    while ((j <= 59)); do
        echo "$j"
        ((j++))
    done
done
