#!/usr/bin/env bash
# Get Apache to run on the container and to return a page
# containing Hello Holberton when querying the root of it.
echo "Hello Holberton" >> /etc/apache2.conf
sudo service apache2 start
